# Configure this Discovery Server
eureka:
  instance:
    hostname: localhost
  client: #Not a client
    registerWithEureka: false
    fetchRegistry: false

# HTTP (Tomcat) port
server:
  port: 1111
eureka:
  server:
    eviction-interval-timer-in-ms: 1000
eureka:
  instance:
    lease-expiration-duration-in-seconds : 90

